# Site settings
title: Las Vegas
client:
  name: Visit Las Vegas
  link: "https://www.visitlasvegas.com"
  link2: "https://www.klm.com/destinations/de/de/north-america/usa/las-vegas"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Vom Rat Pack bis Ocean's Eleven: die pulsierende Hauptstadt Nevadas war schon immer Verführung und Inspiration. ls Oase in der Wüste, Sin City, Heiratsmetropole und Legende im Nachtleben jongliert Vegas mit vielen Identitäten.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/las-vegas" # the subpath of your site, e.g. /blog/
img:     "/de/las-vegas/_assets/img"
css:     "/de/las-vegas/_assets/css"
js:      "/de/las-vegas/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
